#!/bin/bash

# Default files
if [ ! -d "$HOME/.local/share/shadPS4" ]; then
  mkdir -p "$HOME/.local/share/shadPS4"
  cp \
    /defaults/config.json \
    "$HOME/.local/share/shadPS4/"
fi

/opt/shadps4/AppRun
