#!/bin/bash

# Default files
if [ ! -d "$HOME/.local/share/shadPS4" ]; then
  mkdir -p "$HOME/.local/share/shadPS4"
  cp \
    /defaults/config.toml \
    "$HOME/.local/share/shadPS4/"
fi

foot -e /opt/shadps4/AppRun
